bbaseurl = "http://username.github.io"
languageCode = "en-us"
title = "Documenting Texas Music "
theme = "beautifulhugo"
pygmentsUseClasses = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  logo = "img/test.jpg"
  subtitle = "Oral Histories and Interviews"

[Author]
  name = "Dr. Michael Schmidt"
  email = "youremail@domain.com"
  facebook = "username"
  github = "username"
  twitter = "username"
  linkedin = "pub/username/X/YYY/ZZZ"
  stackoverflow = "XXXXXXX/username"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2